import type { CalendarEvent, Client, Lead } from "./types";

/*
 * Accounts, pipeline and calendar.
 *
 * Split out of seed.ts, which was already carrying employees, projects, tasks,
 * leave, notifications and attendance. Ids stay stable — projects reference
 * clients by id, and the client portal signs in against CL-08.
 */

export const seedClients: Client[] = [
  {
    id: "CL-08",
    name: "Northwind Ltd",
    contact: "Daniel Fernandes",
    email: "daniel.f@northwind.co.uk",
    phone: "+44 20 7946 0102",
    industry: "Retail",
    value: 412000,
    since: "2021",
    status: "Active",
    notes: "Two live engagements. Renewal conversation due after the storefront cutover.",
    tone: "blue",
    // The client portal signs in as this account.
    portal: "client",
    createdAt: "2021-03-08",
  },
  {
    id: "CL-12",
    name: "Lumen Health",
    contact: "Anita Desai",
    email: "anita.desai@lumen.health",
    phone: "+44 161 496 0181",
    industry: "Healthcare",
    value: 286500,
    since: "2022",
    status: "Active",
    notes: "Clinical governance sign-off needed before any release touching patient data.",
    tone: "sky",
    createdAt: "2022-06-14",
  },
  {
    id: "CL-15",
    name: "Harbour Logistics",
    contact: "Samuel Barnes",
    email: "s.barnes@harbour.co",
    phone: "+44 151 496 0447",
    industry: "Logistics",
    value: 92500,
    since: "2023",
    status: "Active",
    notes: "Ops desk is the day-to-day contact; Samuel signs off commercially.",
    tone: "orange",
    createdAt: "2023-01-30",
  },
  {
    id: "CL-19",
    name: "Kestrel Bank",
    contact: "Ritu Malhotra",
    email: "r.malhotra@kestrel.bank",
    phone: "+44 20 7946 0918",
    industry: "Financial",
    value: 305000,
    since: "2026",
    status: "Onboarding",
    notes: "Security review cleared. PSD2 certification is the gate on go-live.",
    tone: "slate",
    createdAt: "2026-04-02",
  },
  {
    id: "CL-21",
    name: "Orbit Systems",
    contact: "Leah Cortez",
    email: "leah@orbitsystems.io",
    phone: "+1 415 555 0173",
    industry: "Software",
    value: 64000,
    since: "2025",
    status: "Active",
    notes: "Reselling our dashboard as a paid tier — theming is contractual, not cosmetic.",
    tone: "blue",
    createdAt: "2025-09-11",
  },
  {
    id: "CL-06",
    name: "Vantage Group",
    contact: "Tom Whelan",
    email: "t.whelan@vantagegroup.com",
    phone: "+44 113 496 0220",
    industry: "Consulting",
    value: 78000,
    since: "2020",
    status: "Dormant",
    notes: "CRM migration delivered and closed. Worth a check-in before year end.",
    tone: "slate",
    createdAt: "2020-11-19",
  },
];

export const seedLeads: Lead[] = [
  {
    id: "ld-551",
    code: "LD-551",
    company: "Brightwave Media",
    contact: "Elena Voss",
    email: "elena@brightwave.media",
    phone: "+44 20 7946 0311",
    value: 18000,
    stage: "New",
    source: "Website",
    ownerId: "emp-sneha",
    notes: "Enquiry through the contact form. Wants a marketing site rebuild.",
    createdAt: "2026-07-28",
    updatedAt: "2026-07-28",
  },
  {
    id: "ld-554",
    code: "LD-554",
    company: "Ferro Manufacturing",
    contact: "Hugo Lindqvist",
    email: "h.lindqvist@ferro-mfg.se",
    phone: "+46 8 505 0119",
    value: 46500,
    stage: "New",
    source: "Outbound",
    ownerId: "emp-vikram",
    notes: "Cold outreach, replied same day. Shop-floor tablet app.",
    createdAt: "2026-08-01",
    updatedAt: "2026-08-01",
  },
  {
    id: "ld-547",
    code: "LD-547",
    company: "Anchor Retail",
    contact: "Marcus Bell",
    email: "marcus.bell@anchorretail.com",
    phone: "+44 20 7946 0455",
    value: 62000,
    stage: "Qualified",
    source: "Referral",
    ownerId: "emp-sneha",
    notes: "Referred by Northwind. Budget confirmed, procurement starts September.",
    createdAt: "2026-07-06",
    updatedAt: "2026-07-24",
  },
  {
    id: "ld-549",
    code: "LD-549",
    company: "Pinecrest Schools",
    contact: "Grace Kim",
    email: "g.kim@pinecrest.sch.uk",
    phone: "+44 161 496 0533",
    value: 27400,
    stage: "Qualified",
    source: "Event",
    ownerId: "emp-vikram",
    notes: "Met at EdTech North. Parent portal, term-time delivery window.",
    createdAt: "2026-06-18",
    updatedAt: "2026-07-30",
  },
  {
    id: "ld-541",
    code: "LD-541",
    company: "Solaris Energy",
    contact: "Yusuf Rahman",
    email: "y.rahman@solaris-energy.ae",
    phone: "+971 4 555 0142",
    value: 134000,
    stage: "Proposal",
    source: "Referral",
    ownerId: "emp-sneha",
    notes: "Proposal sent 22 Jul. Decision expected mid-August.",
    createdAt: "2026-05-29",
    updatedAt: "2026-07-22",
  },
  {
    id: "ld-532",
    code: "LD-532",
    company: "Kestrel Bank",
    contact: "Ritu Malhotra",
    email: "r.malhotra@kestrel.bank",
    phone: "+44 20 7946 0918",
    value: 305000,
    stage: "Won",
    source: "Outbound",
    ownerId: "emp-vikram",
    notes: "Closed April. Now an onboarding account.",
    createdAt: "2026-01-14",
    updatedAt: "2026-04-02",
    // Already converted — the account it became.
    clientId: "CL-19",
  },
  {
    id: "ld-538",
    code: "LD-538",
    company: "Calder Insurance",
    contact: "Priya Shah",
    email: "p.shah@calder.co.uk",
    phone: "+44 121 496 0666",
    value: 88000,
    stage: "Lost",
    source: "Outbound",
    ownerId: "emp-sneha",
    notes: "Went with an incumbent supplier on price. Revisit in 12 months.",
    createdAt: "2026-03-11",
    updatedAt: "2026-06-05",
  },
];

/*
 * A working month around the demo clock of 04 Aug 2026.
 *
 * Deliberately spread so clicking almost any weekday in August shows something:
 * a daily standup, project demos, deadlines and a release.
 */
export const seedCalendarEvents: CalendarEvent[] = [
  { id: "cal-01", title: "Daily standup", date: "2026-08-03", time: "09:30", kind: "Standup", createdBy: "Priya Raghavan", createdAt: "2026-07-01" },
  { id: "cal-02", title: "Daily standup", date: "2026-08-04", time: "09:30", kind: "Standup", createdBy: "Priya Raghavan", createdAt: "2026-07-01" },
  { id: "cal-03", title: "Daily standup", date: "2026-08-05", time: "09:30", kind: "Standup", createdBy: "Priya Raghavan", createdAt: "2026-07-01" },
  { id: "cal-04", title: "Daily standup", date: "2026-08-06", time: "09:30", kind: "Standup", createdBy: "Priya Raghavan", createdAt: "2026-07-01" },
  { id: "cal-05", title: "Daily standup", date: "2026-08-07", time: "09:30", kind: "Standup", createdBy: "Priya Raghavan", createdAt: "2026-07-01" },

  { id: "cal-10", title: "Sprint 42 planning", date: "2026-08-04", time: "14:00", kind: "Event", projectId: "prj-northwind", note: "Two-week sprint, checkout and cutover prep.", createdBy: "Karthik Suresh", createdAt: "2026-07-30" },
  { id: "cal-11", title: "Northwind checkout demo", date: "2026-08-07", time: "15:00", kind: "Demo", projectId: "prj-northwind", note: "Walking Daniel through multi-currency checkout.", createdBy: "Priya Raghavan", createdAt: "2026-07-28" },
  { id: "cal-12", title: "Harbour portal deadline", date: "2026-08-08", kind: "Deadline", projectId: "prj-harbour", note: "Consignment tracking table due.", createdBy: "Rohan Kurian", createdAt: "2026-07-14" },
  { id: "cal-13", title: "Payroll cut-off", date: "2026-08-11", kind: "Deadline", note: "Timesheets locked at 17:00.", createdBy: "Aarav Menon", createdAt: "2026-07-02" },
  { id: "cal-14", title: "Kestrel failover walkthrough", date: "2026-08-12", time: "11:00", kind: "Demo", projectId: "prj-kestrel", createdBy: "Karthik Suresh", createdAt: "2026-07-31" },
  { id: "cal-15", title: "Release 2.9", date: "2026-08-14", time: "18:00", kind: "Release", projectId: "prj-lumen", note: "Clinician console and DST fix.", createdBy: "Meera Krishnan", createdAt: "2026-07-20" },
  { id: "cal-16", title: "Lumen clinician console demo", date: "2026-08-18", time: "10:30", kind: "Demo", projectId: "prj-lumen", createdBy: "Priya Raghavan", createdAt: "2026-08-01" },
  { id: "cal-17", title: "QA regression day", date: "2026-08-21", kind: "Event", note: "Full pack across every active project.", createdBy: "Rahul Nair", createdAt: "2026-07-25" },
  { id: "cal-18", title: "Orbit theming deadline", date: "2026-08-21", kind: "Deadline", projectId: "prj-orbit", createdBy: "Rohan Kurian", createdAt: "2026-07-18" },
  { id: "cal-19", title: "All-hands", date: "2026-08-26", time: "16:00", kind: "Event", note: "Half-year numbers and the Kestrel win.", createdBy: "Fazil Niyazdeen", createdAt: "2026-07-10" },
  { id: "cal-20", title: "Northwind parallel-run starts", date: "2026-08-28", kind: "Deadline", projectId: "prj-northwind", createdBy: "Priya Raghavan", createdAt: "2026-07-28" },
  { id: "cal-21", title: "Invoice run", date: "2026-08-28", kind: "Event", createdBy: "Aarav Menon", createdAt: "2026-07-02" },
  { id: "cal-22", title: "Independence Day", date: "2026-08-15", kind: "Holiday", note: "India offices closed.", createdBy: "Aarav Menon", createdAt: "2026-01-05" },
];
